services:
  mysql-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}

volumes:
  db_data: